name: TeamWorkflow

on:
  push:
    branches:
      - main

jobs:
  integration-delivery:
    runs-on: ubuntu-latest
    environment: Test
    defaults:
      run:
        working-directory: todolistexam
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: FTP delivery
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: 21
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: todolistexam/dist/
          server-dir: test/todo
